// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaz7qBHl4n00urYw3i6YYPHzWWjCoiE2c',
    appId: '1:32533061204:web:671e7c560ba651c9e457c1',
    messagingSenderId: '32533061204',
    projectId: 'rideshare-app-388220',
    authDomain: 'rideshare-app-388220.firebaseapp.com',
    storageBucket: 'rideshare-app-388220.appspot.com',
    measurementId: 'G-2V15GHDY9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI7nF6ZA0mi6wZrZBsOfML0JwBC9mfGoU',
    appId: '1:32533061204:android:b540d75b3a053a3de457c1',
    messagingSenderId: '32533061204',
    projectId: 'rideshare-app-388220',
    storageBucket: 'rideshare-app-388220.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2UCrSZ_TEQVgPT2SKiYxm-bFK5qI-5Y0',
    appId: '1:32533061204:ios:9715cfa095ac2225e457c1',
    messagingSenderId: '32533061204',
    projectId: 'rideshare-app-388220',
    storageBucket: 'rideshare-app-388220.appspot.com',
    iosClientId: '32533061204-qaommmu4e4nevo469jca33sd81hit8ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.lastChance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2UCrSZ_TEQVgPT2SKiYxm-bFK5qI-5Y0',
    appId: '1:32533061204:ios:be5a2954a1e7b5eee457c1',
    messagingSenderId: '32533061204',
    projectId: 'rideshare-app-388220',
    storageBucket: 'rideshare-app-388220.appspot.com',
    iosClientId: '32533061204-56p16mnknt116r7lfqp61560nprdpsu7.apps.googleusercontent.com',
    iosBundleId: 'com.example.lastChance.RunnerTests',
  );
}
